package Info.java.lang.object;

/*
 * unique number generated by jvm for every object
 * jvm will store object using hashcode which is by using hashing related algorithm
 * 
 * if the object is stored according to hashCode searching will become very efficient 
 * 
 * if we didn't override the hashCode method then Objcet class hashCode method 
 * will be executed which generates hashCode based on address of the object
 *  hashcode doesnot represent the address of the object
 *  
 *  
 */

public class hashCode {
	static int n=0;
	public int hashCode()
	{/*
			we must override the hashCode method so that every object will get unique number
			
	*/
		return n++; 
	}
public static void main(String[] args) {
	hashCode h=new hashCode();
	System.out.println(h.hashCode());
	hashCode h1=new hashCode();
	System.out.println(h1.hashCode());
	hashCode h2=new hashCode();
	System.out.println(h2.hashCode());
	hashCode h3=new hashCode();
	System.out.println(h3.hashCode());
}
}
